In [18]:
import pandas as pd
import numpy as np


# df_health = pd.read_csv("Climate and Health.csv")

In [19]:
# Load Datasets
import pandas as pd
import numpy as np

try:
    df_health = pd.read_csv("Climate_and_Health.csv")
    print("Climate and Health Data loaded successfully. Shape:", df_health.shape)
except FileNotFoundError:
    print("Error: Climate_and_Health.csv not found.")

try:
    df_solar = pd.read_csv("solar_energy_climate_health_dataset.csv")
    print("Solar Energy Data loaded successfully. Shape:", df_solar.shape)
except FileNotFoundError:
    print("Error: solar_energy_climate_health_dataset.csv not found.")

Climate and Health Data loaded successfully. Shape: (14100, 30)
Solar Energy Data loaded successfully. Shape: (196, 17)

In [20]:
# Clean and Preprocess Data

# 1. Health Data Cleaning
if 'df_health' in locals():
    # Convert date to datetime
    if 'date' in df_health.columns:
        df_health['date'] = pd.to_datetime(df_health['date'])
        print("Converted 'date' to datetime type in Health Data.")

    # Drop duplicates
    initial_rows = len(df_health)
    df_health = df_health.drop_duplicates()
    print(f"Dropped {initial_rows - len(df_health)} duplicates from Health Data.")

    # Handle missing values (Checking only)
    missing_count = df_health.isnull().sum().sum()
    print(f"Total missing values in Health Data: {missing_count}")
    # df_health = df_health.dropna() # Uncomment if you want to drop missing values immediately

    print("Health Data Head:")
    display(df_health.head())

# 2. Solar Data Cleaning
if 'df_solar' in locals():
    initial_rows_solar = len(df_solar)
    df_solar = df_solar.drop_duplicates()
    print(f"Dropped {initial_rows_solar - len(df_solar)} duplicates from Solar Data.")
    
    print("Solar Data Head:")
    display(df_solar.head())

Converted 'date' to datetime type in Health Data.
Dropped 0 duplicates from Health Data.
Total missing values in Health Data: 0
Health Data Head:

,record_id,country_code,country_name,region,income_level,date,year,month,week,latitude,...,air_quality_index,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_admissions,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index
0,1,USA,United States,North America,High,2015-01-04,2015,1,1,37.09,...,82,69.4,31.5,6.6,16.2,1.4,77.3,63627,71.2,90.2
1,2,USA,United States,North America,High,2015-01-11,2015,1,2,37.09,...,6,70.0,26.3,5.2,11.4,0.0,83.6,63627,70.6,94.0
2,3,USA,United States,North America,High,2015-01-18,2015,1,3,37.09,...,137,66.9,33.4,1.3,19.5,0.0,84.7,63627,63.4,100.0
3,4,USA,United States,North America,High,2015-01-25,2015,1,4,37.09,...,-3,47.0,35.0,6.0,9.7,9.0,84.3,63627,68.1,96.4
4,5,USA,United States,North America,High,2015-02-01,2015,2,5,37.09,...,48,61.3,28.3,1.4,22.6,27.3,83.6,63733,69.1,100.0

Dropped 0 duplicates from Solar Data.
Solar Data Head:

,Country,Region,Year,Solar_Capacity_MW,Solar_Generation_GWh,Annual_Growth_Rate_Percent,CO2_Avoided_MetricTons,CO2_Reduction_vs_Baseline_Percent,PM2.5_Reduced_tons,Respiratory_Cases_Avoided,Premature_Deaths_Avoided,Health_Benefits_Million_USD,Air_Quality_Improvement_Index,Population_Million,Solar_Adoption_Rate_Per_GW,Jobs_Created,Solar_Investment_Million_USD
0,Germany,Europe,2010,17390,11700,85.4,8427000,2.3,12400,8500,420,850,0.15,81.8,212.5,150000,35.2
1,Germany,Europe,2011,24700,19000,42.0,13680000,3.5,20100,13800,680,1380,0.22,80.2,212.5,175000,41.8
2,Germany,Europe,2012,32640,28000,32.1,20160000,5.1,29600,20300,1000,2020,0.28,80.3,212.5,195000,48.5
3,Germany,Europe,2013,35700,30000,9.4,21600000,5.5,31700,21700,1070,2170,0.30,80.6,212.5,210000,52.3
4,Germany,Europe,2014,38200,36000,7.0,25920000,6.6,38000,26000,1280,2600,0.35,81.0,212.5,225000,56.8

In [21]:
# Show first 5 rows

df_health.head()

,record_id,country_code,country_name,region,income_level,date,year,month,week,latitude,...,air_quality_index,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_admissions,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index
0,1,USA,United States,North America,High,2015-01-04,2015,1,1,37.09,...,82,69.4,31.5,6.6,16.2,1.4,77.3,63627,71.2,90.2
1,2,USA,United States,North America,High,2015-01-11,2015,1,2,37.09,...,6,70.0,26.3,5.2,11.4,0.0,83.6,63627,70.6,94.0
2,3,USA,United States,North America,High,2015-01-18,2015,1,3,37.09,...,137,66.9,33.4,1.3,19.5,0.0,84.7,63627,63.4,100.0
3,4,USA,United States,North America,High,2015-01-25,2015,1,4,37.09,...,-3,47.0,35.0,6.0,9.7,9.0,84.3,63627,68.1,96.4
4,5,USA,United States,North America,High,2015-02-01,2015,2,5,37.09,...,48,61.3,28.3,1.4,22.6,27.3,83.6,63733,69.1,100.0

In [22]:
df_solar.head()

,Country,Region,Year,Solar_Capacity_MW,Solar_Generation_GWh,Annual_Growth_Rate_Percent,CO2_Avoided_MetricTons,CO2_Reduction_vs_Baseline_Percent,PM2.5_Reduced_tons,Respiratory_Cases_Avoided,Premature_Deaths_Avoided,Health_Benefits_Million_USD,Air_Quality_Improvement_Index,Population_Million,Solar_Adoption_Rate_Per_GW,Jobs_Created,Solar_Investment_Million_USD
0,Germany,Europe,2010,17390,11700,85.4,8427000,2.3,12400,8500,420,850,0.15,81.8,212.5,150000,35.2
1,Germany,Europe,2011,24700,19000,42.0,13680000,3.5,20100,13800,680,1380,0.22,80.2,212.5,175000,41.8
2,Germany,Europe,2012,32640,28000,32.1,20160000,5.1,29600,20300,1000,2020,0.28,80.3,212.5,195000,48.5
3,Germany,Europe,2013,35700,30000,9.4,21600000,5.5,31700,21700,1070,2170,0.30,80.6,212.5,210000,52.3
4,Germany,Europe,2014,38200,36000,7.0,25920000,6.6,38000,26000,1280,2600,0.35,81.0,212.5,225000,56.8

In [23]:
# summary statistics for numeric columns
df_health.describe()

,record_id,date,year,month,week,latitude,longitude,population_millions,temperature_celsius,temp_anomaly_celsius,...,air_quality_index,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_admissions,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index
count,14100.000000,14100,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,...,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000
mean,7050.500000,2020-05-27 11:59:59.999999744,2019.911348,6.437943,26.221631,18.905200,27.349600,217.440000,8.607113,0.120879,...,98.750071,70.016872,30.758596,12.096277,22.172965,6.880794,64.875674,26331.105887,69.874638,93.295780
min,1.000000,2015-01-04 00:00:00,2015.000000,1.000000,1.000000,-38.410000,-106.340000,26.000000,-20.740000,-1.760000,...,-52.000000,21.200000,8.000000,0.000000,0.000000,0.000000,27.900000,1565.000000,47.700000,62.200000
25%,3525.750000,2017-09-15 06:00:00,2017.000000,3.000000,13.000000,4.570000,-3.740000,60.000000,0.257500,-0.220000,...,54.000000,59.200000,27.000000,3.500000,17.800000,0.000000,47.100000,3548.000000,66.500000,88.800000
50%,7050.500000,2020-05-27 12:00:00,2020.000000,6.000000,26.000000,23.630000,22.930000,98.000000,8.630000,0.120000,...,93.000000,69.600000,30.800000,5.800000,22.100000,0.600000,66.600000,13941.000000,70.000000,94.400000
75%,10575.250000,2023-02-06 18:00:00,2023.000000,9.000000,39.000000,37.090000,100.990000,206.000000,16.850000,0.460000,...,142.000000,80.500000,34.500000,8.900000,26.400000,12.300000,81.500000,50206.500000,73.300000,99.700000
max,14100.000000,2025-10-19 00:00:00,2025.000000,12.000000,53.000000,56.130000,138.250000,1411.000000,38.330000,2.120000,...,302.000000,131.800000,51.100000,100.000000,63.000000,59.600000,102.000000,78630.000000,88.700000,100.000000
std,4070.463733,NaN,3.118225,3.421173,14.930110,25.730498,76.062029,355.979373,11.289938,0.506365,...,59.143284,15.223261,5.605436,17.146545,6.609017,9.498276,18.230095,26329.114275,5.025983,6.295667

In [24]:
df_solar.describe()

,Year,Solar_Capacity_MW,Solar_Generation_GWh,Annual_Growth_Rate_Percent,CO2_Avoided_MetricTons,CO2_Reduction_vs_Baseline_Percent,PM2.5_Reduced_tons,Respiratory_Cases_Avoided,Premature_Deaths_Avoided,Health_Benefits_Million_USD,Air_Quality_Improvement_Index,Population_Million,Solar_Adoption_Rate_Per_GW,Jobs_Created,Solar_Investment_Million_USD
count,196.000000,196.000000,196.000000,196.000000,1.960000e+02,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,196.000000,1.960000e+02,196.000000
mean,2016.500000,29760.714286,29823.724490,49.424490,2.147294e+07,6.043367,31481.484694,21479.030612,1060.862245,2147.556122,0.547194,281.309694,796.545918,1.063896e+06,46.460714
std,4.041452,64347.900087,65214.657926,67.194255,4.695453e+07,7.861383,68850.054373,46951.364091,2308.901134,4695.182585,0.936425,445.183737,274.348945,4.495270e+06,55.249538
min,2010.000000,20.000000,10.000000,0.000000,7.200000e+03,0.000000,11.000000,7.000000,0.000000,1.000000,0.000000,22.000000,212.500000,2.000000e+02,0.100000
25%,2013.000000,3575.000000,2500.000000,13.825000,1.800000e+06,0.800000,2640.000000,1804.500000,85.250000,180.000000,0.070000,58.150000,600.000000,2.500000e+04,8.725000
50%,2016.500000,11950.000000,11000.000000,30.750000,7.920000e+06,4.000000,11616.000000,7928.000000,372.500000,793.000000,0.290000,74.550000,857.100000,6.500000e+04,32.500000
75%,2020.000000,26375.000000,27000.000000,60.000000,1.944000e+07,8.050000,28512.000000,19440.000000,990.250000,1944.000000,0.542500,203.525000,1032.625000,1.775000e+05,59.925000
max,2023.000000,609000.000000,585000.000000,650.000000,4.212000e+08,59.300000,617700.000000,421200.000000,20662.000000,42120.000000,7.780000,1425.700000,1250.000000,3.800000e+07,385.200000

In [25]:
#  it summarizes all columns, including categorical (string/object) ones.
df_health.describe(include="all")

,record_id,country_code,country_name,region,income_level,date,year,month,week,latitude,...,air_quality_index,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_admissions,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index
count,14100.000000,14100,14100,14100,14100,14100,14100.000000,14100.000000,14100.000000,14100.000000,...,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000
unique,NaN,25,25,8,3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,USA,United States,Europe,High,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,564,564,2820,5076,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,7050.500000,NaN,NaN,NaN,NaN,2020-05-27 11:59:59.999999744,2019.911348,6.437943,26.221631,18.905200,...,98.750071,70.016872,30.758596,12.096277,22.172965,6.880794,64.875674,26331.105887,69.874638,93.295780
min,1.000000,NaN,NaN,NaN,NaN,2015-01-04 00:00:00,2015.000000,1.000000,1.000000,-38.410000,...,-52.000000,21.200000,8.000000,0.000000,0.000000,0.000000,27.900000,1565.000000,47.700000,62.200000
25%,3525.750000,NaN,NaN,NaN,NaN,2017-09-15 06:00:00,2017.000000,3.000000,13.000000,4.570000,...,54.000000,59.200000,27.000000,3.500000,17.800000,0.000000,47.100000,3548.000000,66.500000,88.800000
50%,7050.500000,NaN,NaN,NaN,NaN,2020-05-27 12:00:00,2020.000000,6.000000,26.000000,23.630000,...,93.000000,69.600000,30.800000,5.800000,22.100000,0.600000,66.600000,13941.000000,70.000000,94.400000
75%,10575.250000,NaN,NaN,NaN,NaN,2023-02-06 18:00:00,2023.000000,9.000000,39.000000,37.090000,...,142.000000,80.500000,34.500000,8.900000,26.400000,12.300000,81.500000,50206.500000,73.300000,99.700000
max,14100.000000,NaN,NaN,NaN,NaN,2025-10-19 00:00:00,2025.000000,12.000000,53.000000,56.130000,...,302.000000,131.800000,51.100000,100.000000,63.000000,59.600000,102.000000,78630.000000,88.700000,100.000000
std,4070.463733,NaN,NaN,NaN,NaN,NaN,3.118225,3.421173,14.930110,25.730498,...,59.143284,15.223261,5.605436,17.146545,6.609017,9.498276,18.230095,26329.114275,5.025983,6.295667

In [26]:

# overview of columns, data types, non-null counts
df_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     14100 non-null  int64
 1   country_code                  14100 non-null  object
 2   country_name                  14100 non-null  object
 3   region                        14100 non-null  object
 4   income_level                  14100 non-null  object
 5   date                          14100 non-null  datetime64[ns]
 6   year                          14100 non-null  int64
 7   month                         14100 non-null  int64
 8   week                          14100 non-null  int64
 9   latitude                      14100 non-null  float64
 10  longitude                     14100 non-null  float64
 11  population_millions           14100 non-null  int64
 12  temperature_celsius           14100 non-null  float64
 13  temp_anomaly_celsius          14100 non-null  float64
 14  precipitation_mm              14100 non-null  float64
 15  heat_wave_days                14100 non-null  int64
 16  drought_indicator             14100 non-null  int64
 17  flood_indicator               14100 non-null  int64
 18  extreme_weather_events        14100 non-null  int64
 19  pm25_ugm3                     14100 non-null  float64
 20  air_quality_index             14100 non-null  int64
 21  respiratory_disease_rate      14100 non-null  float64
 22  cardio_mortality_rate         14100 non-null  float64
 23  vector_disease_risk_score     14100 non-null  float64
 24  waterborne_disease_incidents  14100 non-null  float64
 25  heat_related_admissions       14100 non-null  float64
 26  healthcare_access_index       14100 non-null  float64
 27  gdp_per_capita_usd            14100 non-null  int64
 28  mental_health_index           14100 non-null  float64
 29  food_security_index           14100 non-null  float64
dtypes: datetime64[ns](1), float64(14), int64(11), object(4)
memory usage: 3.2+ MB

In [27]:
# list of all column names
df_health.columns

Index(['record_id', 'country_code', 'country_name', 'region', 'income_level',
       'date', 'year', 'month', 'week', 'latitude', 'longitude',
       'population_millions', 'temperature_celsius', 'temp_anomaly_celsius',
       'precipitation_mm', 'heat_wave_days', 'drought_indicator',
       'flood_indicator', 'extreme_weather_events', 'pm25_ugm3',
       'air_quality_index', 'respiratory_disease_rate',
       'cardio_mortality_rate', 'vector_disease_risk_score',
       'waterborne_disease_incidents', 'heat_related_admissions',
       'healthcare_access_index', 'gdp_per_capita_usd', 'mental_health_index',
       'food_security_index'],
      dtype='object')

In [28]:
df_health = df_health.rename(columns={
    'heat_related_admissions': 'heat_related_illnesses'
})

In [29]:
df_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     14100 non-null  int64
 1   country_code                  14100 non-null  object
 2   country_name                  14100 non-null  object
 3   region                        14100 non-null  object
 4   income_level                  14100 non-null  object
 5   date                          14100 non-null  datetime64[ns]
 6   year                          14100 non-null  int64
 7   month                         14100 non-null  int64
 8   week                          14100 non-null  int64
 9   latitude                      14100 non-null  float64
 10  longitude                     14100 non-null  float64
 11  population_millions           14100 non-null  int64
 12  temperature_celsius           14100 non-null  float64
 13  temp_anomaly_celsius          14100 non-null  float64
 14  precipitation_mm              14100 non-null  float64
 15  heat_wave_days                14100 non-null  int64
 16  drought_indicator             14100 non-null  int64
 17  flood_indicator               14100 non-null  int64
 18  extreme_weather_events        14100 non-null  int64
 19  pm25_ugm3                     14100 non-null  float64
 20  air_quality_index             14100 non-null  int64
 21  respiratory_disease_rate      14100 non-null  float64
 22  cardio_mortality_rate         14100 non-null  float64
 23  vector_disease_risk_score     14100 non-null  float64
 24  waterborne_disease_incidents  14100 non-null  float64
 25  heat_related_illnesses        14100 non-null  float64
 26  healthcare_access_index       14100 non-null  float64
 27  gdp_per_capita_usd            14100 non-null  int64
 28  mental_health_index           14100 non-null  float64
 29  food_security_index           14100 non-null  float64
dtypes: datetime64[ns](1), float64(14), int64(11), object(4)
memory usage: 3.2+ MB

In [30]:
df_health['date'].dtype

dtype('<M8[ns]')

In [31]:
df_health['date'] = pd.to_datetime(df_health['date'])

In [32]:
df_health['date'].dtype

dtype('<M8[ns]')

In [33]:
df_health['region'].dtype

dtype('O')

In [34]:
cat_cols = ['country_code', 'country_name', 'region', 'income_level']

for col in cat_cols:
    df_health[col] = df_health[col].astype('category')

In [35]:
df_health['region'].dtype

CategoricalDtype(categories=['Africa', 'East Asia', 'Europe', 'North America', 'Oceania',
                  'South America', 'South Asia', 'Southeast Asia'],
, ordered=False, categories_dtype=object)

In [36]:
df_health['population_millions'].dtype

dtype('int64')

In [37]:
df_health['population_millions'].head(10)

0    331
1    331
2    331
3    331
4    331
5    331
6    331
7    331
8    331
9    331
Name: population_millions, dtype: int64

In [38]:
df_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     14100 non-null  int64
 1   country_code                  14100 non-null  category
 2   country_name                  14100 non-null  category
 3   region                        14100 non-null  category
 4   income_level                  14100 non-null  category
 5   date                          14100 non-null  datetime64[ns]
 6   year                          14100 non-null  int64
 7   month                         14100 non-null  int64
 8   week                          14100 non-null  int64
 9   latitude                      14100 non-null  float64
 10  longitude                     14100 non-null  float64
 11  population_millions           14100 non-null  int64
 12  temperature_celsius           14100 non-null  float64
 13  temp_anomaly_celsius          14100 non-null  float64
 14  precipitation_mm              14100 non-null  float64
 15  heat_wave_days                14100 non-null  int64
 16  drought_indicator             14100 non-null  int64
 17  flood_indicator               14100 non-null  int64
 18  extreme_weather_events        14100 non-null  int64
 19  pm25_ugm3                     14100 non-null  float64
 20  air_quality_index             14100 non-null  int64
 21  respiratory_disease_rate      14100 non-null  float64
 22  cardio_mortality_rate         14100 non-null  float64
 23  vector_disease_risk_score     14100 non-null  float64
 24  waterborne_disease_incidents  14100 non-null  float64
 25  heat_related_illnesses        14100 non-null  float64
 26  healthcare_access_index       14100 non-null  float64
 27  gdp_per_capita_usd            14100 non-null  int64
 28  mental_health_index           14100 non-null  float64
 29  food_security_index           14100 non-null  float64
dtypes: category(4), datetime64[ns](1), float64(14), int64(11)
memory usage: 2.9 MB

In [39]:
# Show the shape (rows, columns)
df_health.shape

(14100, 30)

In [40]:
df_health["temperature_celsius"]

0         4.59
1         3.13
2         3.99
3         6.43
4         9.00
         ...
14095    14.34
14096    14.35
14097    13.50
14098    15.18
14099    14.12
Name: temperature_celsius, Length: 14100, dtype: float64

In [41]:
df_health["heat_wave_days"].nlargest(10)

7809     5
62       4
940      4
1257     4
1921     4
3038     4
5297     4
5393     4
9650     4
10774    4
Name: heat_wave_days, dtype: int64

In [42]:
# Top 5 highest temperatures

df_health['temperature_celsius'].nlargest(5)

7197    38.33
5917    37.63
6835    37.43
7153    37.35
5963    37.23
Name: temperature_celsius, dtype: float64

In [43]:
# Top 10 Highest Temperatures using groupby (Country + Year)
top_10_temp = (
    df_health.groupby(['country_name', 'year'])['temperature_celsius']
      .mean()                      # use .max() if you want peak temperature
      .reset_index()
      .sort_values(by='temperature_celsius', ascending=False)
      .head(10)
)

top_10_temp

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14028\4025164824.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_health.groupby(['country_name', 'year'])['temperature_celsius']

    country_name  year  temperature_celsius
164        Kenya  2025            26.160238
131    Indonesia  2025            25.805714
161        Kenya  2022            25.635192
155        Kenya  2016            25.449231
162        Kenya  2023            25.317358
157        Kenya  2018            25.246538
129    Indonesia  2023            25.137736
163        Kenya  2024            25.130192
159        Kenya  2020            25.050192
160        Kenya  2021            25.035192

In [44]:
# Group by Year and Calculate Average Temperature

df_year_temp = df_health.groupby("year")["temperature_celsius"].mean().reset_index()

In [45]:
df_year_temp.head()

   year  temperature_celsius
0  2015             8.484069
1  2016             8.490838
2  2017             8.451117
3  2018             8.358238
4  2019             8.554238

In [46]:
df_year_temp.tail()

    year  temperature_celsius
6   2021             8.465738
7   2022             8.632915
8   2023             8.615185
9   2024             8.632231
10  2025             9.662543

In [47]:
df_health['climate_risk_category'] = pd.cut(
    df_health['heat_wave_days'],
    bins=[-1, 5, 15, 30, np.inf],
    labels=['Low', 'Moderate', 'High', 'Extreme']
)

df_health[['heat_wave_days', 'climate_risk_category']].head()

   heat_wave_days climate_risk_category
0               0                   Low
1               0                   Low
2               0                   Low
3               0                   Low
4               1                   Low

In [48]:
df_health.head()

,record_id,country_code,country_name,region,income_level,date,year,month,week,latitude,...,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_illnesses,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index,climate_risk_category
0,1,USA,United States,North America,High,2015-01-04,2015,1,1,37.09,...,69.4,31.5,6.6,16.2,1.4,77.3,63627,71.2,90.2,Low
1,2,USA,United States,North America,High,2015-01-11,2015,1,2,37.09,...,70.0,26.3,5.2,11.4,0.0,83.6,63627,70.6,94.0,Low
2,3,USA,United States,North America,High,2015-01-18,2015,1,3,37.09,...,66.9,33.4,1.3,19.5,0.0,84.7,63627,63.4,100.0,Low
3,4,USA,United States,North America,High,2015-01-25,2015,1,4,37.09,...,47.0,35.0,6.0,9.7,9.0,84.3,63627,68.1,96.4,Low
4,5,USA,United States,North America,High,2015-02-01,2015,2,5,37.09,...,61.3,28.3,1.4,22.6,27.3,83.6,63733,69.1,100.0,Low

In [49]:
df_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     14100 non-null  int64
 1   country_code                  14100 non-null  category
 2   country_name                  14100 non-null  category
 3   region                        14100 non-null  category
 4   income_level                  14100 non-null  category
 5   date                          14100 non-null  datetime64[ns]
 6   year                          14100 non-null  int64
 7   month                         14100 non-null  int64
 8   week                          14100 non-null  int64
 9   latitude                      14100 non-null  float64
 10  longitude                     14100 non-null  float64
 11  population_millions           14100 non-null  int64
 12  temperature_celsius           14100 non-null  float64
 13  temp_anomaly_celsius          14100 non-null  float64
 14  precipitation_mm              14100 non-null  float64
 15  heat_wave_days                14100 non-null  int64
 16  drought_indicator             14100 non-null  int64
 17  flood_indicator               14100 non-null  int64
 18  extreme_weather_events        14100 non-null  int64
 19  pm25_ugm3                     14100 non-null  float64
 20  air_quality_index             14100 non-null  int64
 21  respiratory_disease_rate      14100 non-null  float64
 22  cardio_mortality_rate         14100 non-null  float64
 23  vector_disease_risk_score     14100 non-null  float64
 24  waterborne_disease_incidents  14100 non-null  float64
 25  heat_related_illnesses        14100 non-null  float64
 26  healthcare_access_index       14100 non-null  float64
 27  gdp_per_capita_usd            14100 non-null  int64
 28  mental_health_index           14100 non-null  float64
 29  food_security_index           14100 non-null  float64
 30  climate_risk_category         14100 non-null  category
dtypes: category(5), datetime64[ns](1), float64(14), int64(11)
memory usage: 2.9 MB

In [50]:
# Year-Wise Average Temperature Trend
yearly_temp = df_health.groupby('year')['temperature_celsius'].mean()

In [51]:
# Climate vs Health Relationship
df_health.groupby('year')['respiratory_disease_rate'].mean()

year
2015    69.895846
2016    70.044769
2017    70.064075
2018    70.201923
2019    70.190692
2020    70.144692
2021    70.079538
2022    70.137077
2023    70.321962
2024    69.352769
2025    69.680857
Name: respiratory_disease_rate, dtype: float64

In [52]:
df_health.describe(include = 'all')

,record_id,country_code,country_name,region,income_level,date,year,month,week,latitude,...,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_illnesses,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index,climate_risk_category
count,14100.000000,14100,14100,14100,14100,14100,14100.000000,14100.000000,14100.000000,14100.000000,...,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100
unique,NaN,25,25,8,3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
top,NaN,ARG,Argentina,Europe,High,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low
freq,NaN,564,564,2820,5076,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14100
mean,7050.500000,NaN,NaN,NaN,NaN,2020-05-27 11:59:59.999999744,2019.911348,6.437943,26.221631,18.905200,...,70.016872,30.758596,12.096277,22.172965,6.880794,64.875674,26331.105887,69.874638,93.295780,NaN
min,1.000000,NaN,NaN,NaN,NaN,2015-01-04 00:00:00,2015.000000,1.000000,1.000000,-38.410000,...,21.200000,8.000000,0.000000,0.000000,0.000000,27.900000,1565.000000,47.700000,62.200000,NaN
25%,3525.750000,NaN,NaN,NaN,NaN,2017-09-15 06:00:00,2017.000000,3.000000,13.000000,4.570000,...,59.200000,27.000000,3.500000,17.800000,0.000000,47.100000,3548.000000,66.500000,88.800000,NaN
50%,7050.500000,NaN,NaN,NaN,NaN,2020-05-27 12:00:00,2020.000000,6.000000,26.000000,23.630000,...,69.600000,30.800000,5.800000,22.100000,0.600000,66.600000,13941.000000,70.000000,94.400000,NaN
75%,10575.250000,NaN,NaN,NaN,NaN,2023-02-06 18:00:00,2023.000000,9.000000,39.000000,37.090000,...,80.500000,34.500000,8.900000,26.400000,12.300000,81.500000,50206.500000,73.300000,99.700000,NaN
max,14100.000000,NaN,NaN,NaN,NaN,2025-10-19 00:00:00,2025.000000,12.000000,53.000000,56.130000,...,131.800000,51.100000,100.000000,63.000000,59.600000,102.000000,78630.000000,88.700000,100.000000,NaN
std,4070.463733,NaN,NaN,NaN,NaN,NaN,3.118225,3.421173,14.930110,25.730498,...,15.223261,5.605436,17.146545,6.609017,9.498276,18.230095,26329.114275,5.025983,6.295667,NaN

In [1]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details

username = "postgres"        # default user
password = "pass"        # the password you set during installation
host = "localhost"           # if running locally
port = "5432"                # default PostgreSQL port
database = "Climate_and_Health"   # the database you created in pgAdmin

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL
table_name = "climate"      # choose any table name

df_.to_sql(table_name, engine, if_exists="replace", index=False)

print(
    f"Data successfully loaded into table '{table_name}' in database '{database}'."
)

NameError: name 'df_' is not defined

In [54]:
df_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     14100 non-null  int64
 1   country_code                  14100 non-null  category
 2   country_name                  14100 non-null  category
 3   region                        14100 non-null  category
 4   income_level                  14100 non-null  category
 5   date                          14100 non-null  datetime64[ns]
 6   year                          14100 non-null  int64
 7   month                         14100 non-null  int64
 8   week                          14100 non-null  int64
 9   latitude                      14100 non-null  float64
 10  longitude                     14100 non-null  float64
 11  population_millions           14100 non-null  int64
 12  temperature_celsius           14100 non-null  float64
 13  temp_anomaly_celsius          14100 non-null  float64
 14  precipitation_mm              14100 non-null  float64
 15  heat_wave_days                14100 non-null  int64
 16  drought_indicator             14100 non-null  int64
 17  flood_indicator               14100 non-null  int64
 18  extreme_weather_events        14100 non-null  int64
 19  pm25_ugm3                     14100 non-null  float64
 20  air_quality_index             14100 non-null  int64
 21  respiratory_disease_rate      14100 non-null  float64
 22  cardio_mortality_rate         14100 non-null  float64
 23  vector_disease_risk_score     14100 non-null  float64
 24  waterborne_disease_incidents  14100 non-null  float64
 25  heat_related_illnesses        14100 non-null  float64
 26  healthcare_access_index       14100 non-null  float64
 27  gdp_per_capita_usd            14100 non-null  int64
 28  mental_health_index           14100 non-null  float64
 29  food_security_index           14100 non-null  float64
 30  climate_risk_category         14100 non-null  category
dtypes: category(5), datetime64[ns](1), float64(14), int64(11)
memory usage: 2.9 MB

In [55]:
df_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     14100 non-null  int64
 1   country_code                  14100 non-null  category
 2   country_name                  14100 non-null  category
 3   region                        14100 non-null  category
 4   income_level                  14100 non-null  category
 5   date                          14100 non-null  datetime64[ns]
 6   year                          14100 non-null  int64
 7   month                         14100 non-null  int64
 8   week                          14100 non-null  int64
 9   latitude                      14100 non-null  float64
 10  longitude                     14100 non-null  float64
 11  population_millions           14100 non-null  int64
 12  temperature_celsius           14100 non-null  float64
 13  temp_anomaly_celsius          14100 non-null  float64
 14  precipitation_mm              14100 non-null  float64
 15  heat_wave_days                14100 non-null  int64
 16  drought_indicator             14100 non-null  int64
 17  flood_indicator               14100 non-null  int64
 18  extreme_weather_events        14100 non-null  int64
 19  pm25_ugm3                     14100 non-null  float64
 20  air_quality_index             14100 non-null  int64
 21  respiratory_disease_rate      14100 non-null  float64
 22  cardio_mortality_rate         14100 non-null  float64
 23  vector_disease_risk_score     14100 non-null  float64
 24  waterborne_disease_incidents  14100 non-null  float64
 25  heat_related_illnesses        14100 non-null  float64
 26  healthcare_access_index       14100 non-null  float64
 27  gdp_per_capita_usd            14100 non-null  int64
 28  mental_health_index           14100 non-null  float64
 29  food_security_index           14100 non-null  float64
 30  climate_risk_category         14100 non-null  category
dtypes: category(5), datetime64[ns](1), float64(14), int64(11)
memory usage: 2.9 MB

In [56]:
df_health.to_csv('output.csv', index=False) 
 # Replace 'df' with your DataFrame name; index=False avoids extra column